name: narafinder
dependencies:
  - python=3.9
  - pip
  - pip:
    - rasterio==1.3.9
    - numpy==1.23.5
    - matplotlib==3.7.0
    - opencv-python==4.6.0.66
    - fiona==1.9.5
    - shapely==2.0.2
    - customtkinter==5.2.2
    - pyproj==3.6.1